name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Deploy to IPFS
        run: |
          npm install -g ipfs-deploy
          curl https://ipfs-deploy.pages.dev/ipfs-cluster.js > "/opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/ipfs-deploy/src/pinners/ipfs-cluster.js"
          ipfs-deploy -C -p ipfs-cluster -d cloudflare ./

